Repository camel-tooling/camel-lsp-client-vscode, pull requests merged in 2020-04, with the labels that each got.

#301 FUSETOOLS2-347 - Upgrade to Camel 3.2 (changelog)
  Changelog.md
Labels: READY FOR REVIEW

#305 FUSETOOLS2-350 - specify current latest compatible VS Code version for
  package.json
Labels: PRIO, READY FOR REVIEW

#309 Temporary skip Status Bar UI tests to avoid repeating flaky build failures
  src/ui-test/lsp_extension_test.ts
Labels: READY FOR REVIEW

#317 Bump vcode-extension-tester version from 2.6.0 to 2.6.2
  package-lock.json
  package.json
Labels: READY FOR REVIEW, dependencies
